import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerListCredentialsTool }              from "./list-credentials.js";
import { registerSetCredentialTool }                from "./set-credential.js";
import { registerListProjectsTool }                 from "./list-projects.js";
import { registerGetProjectTool }                   from "./get-project.js";
import { registerNewProjectTool }                   from "./new-project.js";
import { registerListProjectTemplatesTool }         from "./list-project-templates.js";
import { registerNewProjectTemplateTool }           from "./new-project-template.js";
import { registerRemoveProjectTemplateTool }        from "./remove-project-template.js";
import { registerListTmsTool }                      from "./list-tms.js";
import { registerGetTmTool }                        from "./get-tm.js";
import { registerNewTmTool }                        from "./new-tm.js";
import { registerRemoveTmTool }                     from "./remove-tm.js";
import { registerImportTmTool }                     from "./import-tm.js";
import { registerExportTmTool }                     from "./export-tm.js";
import { registerListLocationsTool }                from "./list-locations.js";
import { registerListCustomersTool }                from "./list-customers.js";
import { registerNewCustomerTool }                  from "./new-customer.js";
import { registerUpdateCustomerTool }               from "./update-customer.js";
import { registerRemoveCustomerTool }               from "./remove-customer.js";
import { registerListWorkflowsTool }                from "./list-workflows.js";
import { registerListTranslationEnginesTool }       from "./list-translation-engines.js";
import { registerListFileTypeConfigurationsTool }   from "./list-file-type-configurations.js";
import { registerListLanguageProcessingRulesTool }  from "./list-language-processing-rules.js";
import { registerListFieldTemplatesTool }            from "./list-field-templates.js";
import { registerListPricingModelsTool }             from "./list-pricing-models.js";
import { registerListScheduleTemplatesTool }         from "./list-schedule-templates.js";
import { registerListSupportedLanguagesTool }        from "./list-supported-languages.js";
import { registerListGroupsTool }                    from "./list-groups.js";
import { registerListTermbasesTool }                from "./list-termbases.js";
import { registerListUsersTool }                    from "./list-users.js";
import { registerNewTermbaseTool }                  from "./new-termbase.js";
import { registerImportTermbaseTool }               from "./import-termbase.js";
import { registerExportTermbaseTool }               from "./export-termbase.js";

export function registerLanguageCloudTools(server: McpServer) {
  registerListCredentialsTool(server);
  registerSetCredentialTool(server);
  registerListProjectsTool(server);
  registerGetProjectTool(server);
  registerNewProjectTool(server);
  registerListProjectTemplatesTool(server);
  registerNewProjectTemplateTool(server);
  registerRemoveProjectTemplateTool(server);
  registerListTmsTool(server);
  registerGetTmTool(server);
  registerNewTmTool(server);
  registerRemoveTmTool(server);
  registerImportTmTool(server);
  registerExportTmTool(server);
  registerListLocationsTool(server);
  registerListCustomersTool(server);
  registerNewCustomerTool(server);
  registerUpdateCustomerTool(server);
  registerRemoveCustomerTool(server);
  registerListWorkflowsTool(server);
  registerListTranslationEnginesTool(server);
  registerListFileTypeConfigurationsTool(server);
  registerListLanguageProcessingRulesTool(server);
  registerListFieldTemplatesTool(server);
  registerListPricingModelsTool(server);
  registerListScheduleTemplatesTool(server);
  registerListSupportedLanguagesTool(server);
  registerListGroupsTool(server);
  registerListTermbasesTool(server);
  registerListUsersTool(server);
  registerNewTermbaseTool(server);
  registerImportTermbaseTool(server);
  registerExportTermbaseTool(server);
}
