import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerListCredentialsTool }       from "./list-credentials.js";
import { registerSetCredentialTool }         from "./set-credential.js";
import { registerListProjectsTool }          from "./list-projects.js";
import { registerGetProjectTool }            from "./get-project.js";
import { registerNewProjectTool }            from "./new-project.js";
import { registerUpdateProjectStatusTool }   from "./update-project-status.js";
import { registerExportPackageTool }         from "./export-package.js";
import { registerImportPackageTool }         from "./import-package.js";
import { registerGetAnalysisReportTool }     from "./get-analysis-report.js";
import { registerSaveProjectFilesTool }      from "./save-project-files.js";
import { registerListTmsTool }               from "./list-tms.js";
import { registerNewTmTool }                 from "./new-tm.js";
import { registerImportTmxTool }             from "./import-tmx.js";
import { registerExportTmxTool }             from "./export-tmx.js";
import { registerListProjectTemplatesTool }  from "./list-project-templates.js";
import { registerListOrganizationsTool }     from "./list-organizations.js";
import { registerListUsersTool }             from "./list-users.js";
import { registerGetBackgroundTasksTool }    from "./get-background-tasks.js";
import { registerNewUserTool }               from "./new-user.js";
import { registerUpdateUserTool }            from "./update-user.js";
import { registerNewRoleTool }               from "./new-role.js";
import { registerUpdateRoleToUserTool }      from "./update-role-to-user.js";
import { registerMoveOrganizationResourcesTool } from "./move-organization-resources.js";

export function registerGroupShareTools(server: McpServer) {
  registerListCredentialsTool(server);
  registerSetCredentialTool(server);
  registerListProjectsTool(server);
  registerGetProjectTool(server);
  registerNewProjectTool(server);
  registerUpdateProjectStatusTool(server);
  registerExportPackageTool(server);
  registerImportPackageTool(server);
  registerGetAnalysisReportTool(server);
  registerSaveProjectFilesTool(server);
  registerListTmsTool(server);
  registerNewTmTool(server);
  registerImportTmxTool(server);
  registerExportTmxTool(server);
  registerListProjectTemplatesTool(server);
  registerListOrganizationsTool(server);
  registerListUsersTool(server);
  registerGetBackgroundTasksTool(server);
  registerNewUserTool(server);
  registerUpdateUserTool(server);
  registerNewRoleTool(server);
  registerUpdateRoleToUserTool(server);
  registerMoveOrganizationResourcesTool(server);
}
